//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.239
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Umc.Core {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionRS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionRS() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Umc.Core.ExceptionRS", typeof(ExceptionRS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   ILoadable 인터페이스는 해당 데이터 소스를 로드할 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ILoadable_인터페이스는_해당_데이터소스를_로드할수없습니다 {
            get {
                return ResourceManager.GetString("ILoadable_인터페이스는_해당_데이터소스를_로드할수없습니다", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} 특성이 {1} 개 이상인 경우 반드시 {2} 특성을 선언해야 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string O_가_1_개_이상인경우_반드시_2_특성을_선언해야합니다 {
            get {
                return ResourceManager.GetString("O_가_1_개_이상인경우_반드시_2_특성을_선언해야합니다", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} 값이 {1} 입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string O_값이_1_입니다 {
            get {
                return ResourceManager.GetString("O_값이_1_입니다", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} 는 {1} 로 변환할 수 없습니다. {0} 형식이 잘못되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string O_는_1_로_변환할수_없습니다_O_형식이_잘못되었습니다 {
            get {
                return ResourceManager.GetString("O_는_1_로_변환할수_없습니다_O_형식이_잘못되었습니다", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} 동적 프락시 어셈블리는 저장할 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string O_동적프락시_어셈블리는_저장할수없습니다 {
            get {
                return ResourceManager.GetString("O_동적프락시_어셈블리는_저장할수없습니다", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} 어셈블리는 강력한 이름의 서명이 되어있지않아 공개키토큰 값이 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string O_어셈블리는_강력한_이름의_서명이_되어있지않아_공개키토큰_값이_없습니다 {
            get {
                return ResourceManager.GetString("O_어셈블리는_강력한_이름의_서명이_되어있지않아_공개키토큰_값이_없습니다", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} 어셈블리에서 {1} 특성을 찾을 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string O_어셈블리에서_1_특성을_찾을_수_없습니다 {
            get {
                return ResourceManager.GetString("O_어셈블리에서_1_특성을_찾을_수_없습니다", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} 을 찾을 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string O_을_찾을_수_없습니다 {
            get {
                return ResourceManager.GetString("O_을_찾을_수_없습니다", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} 의 개수가 맞지 않습니다. {1} != {2}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string O_의_개수가_맞지_않습니다_1_2 {
            get {
                return ResourceManager.GetString("O_의_개수가_맞지_않습니다_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} 특성은 {1} 보다 많을 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string O_특성은_1_보다_많을수_없습니다 {
            get {
                return ResourceManager.GetString("O_특성은_1_보다_많을수_없습니다", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} 특성은 {1} 에 {2} 개만 선언할 수 있습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string O_특성은_1_에_2_개만_선언할수있습니다 {
            get {
                return ResourceManager.GetString("O_특성은_1_에_2_개만_선언할수있습니다", resourceCulture);
            }
        }
        
        /// <summary>
        ///   매핑 속성의 개수가 일치하지 않습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 매핑_속성의_개수가_일치하지_않습니다 {
            get {
                return ResourceManager.GetString("매핑_속성의_개수가_일치하지_않습니다", resourceCulture);
            }
        }
        
        /// <summary>
        ///   정적 타입의 ITypeLambda는 개체를 생성할 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 정적_타입의_ITypeLambda는_개체를_생성할_수_없습니다 {
            get {
                return ResourceManager.GetString("정적_타입의_ITypeLambda는_개체를_생성할_수_없습니다", resourceCulture);
            }
        }
        
        /// <summary>
        ///   키 {0}는 매핑 대상 키가 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 키_O는_매핑_대상_키가_없습니다 {
            get {
                return ResourceManager.GetString("키_O는_매핑_대상_키가_없습니다", resourceCulture);
            }
        }
        
        /// <summary>
        ///   키 {0}는 필수 매핑 키 입니다. 이 매핑 키가 대상 데이터소스에 존재하지 않아 매핑할 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 키_O는_필수_매핑키_입니다_이_매핑키가_대상_데이터소스에_존재하지않아_매핑할_수_없습니다 {
            get {
                return ResourceManager.GetString("키_O는_필수_매핑키_입니다_이_매핑키가_대상_데이터소스에_존재하지않아_매핑할_수_없습니다", resourceCulture);
            }
        }
    }
}
