// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.0.38967
//    <NameSpace>Umc.Core.ioc.Configuration</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>True</GenerateXMLAttributes><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>True</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>False</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace Umc.Core.IoC.Configuration
{
	using System;
	using System.Diagnostics;
	using System.Xml.Serialization;
	using System.Collections;
	using System.Xml.Schema;
	using System.ComponentModel;
	using System.Collections.Generic;


	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schema.powerumc.kr/umc/core/ioc")]
	[System.Xml.Serialization.XmlRootAttribute("Umc.Core.ioc", Namespace = "http://schema.powerumc.kr/umc/core/ioc", IsNullable = false)]
	public partial class UmcCoreIoCElement
	{

		private List<ContainerElement> containersField;

		[System.Xml.Serialization.XmlArrayAttribute(Order = 0)]
		[System.Xml.Serialization.XmlArrayItemAttribute("container", IsNullable = false)]
		public List<ContainerElement> containers
		{
			get
			{
				return this.containersField;
			}
			set
			{
				this.containersField = value;
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schema.powerumc.kr/umc/core/ioc")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schema.powerumc.kr/umc/core/ioc", IsNullable = true)]
	public partial class ContainerElement
	{

		private List<RegisterElement> registerField;

		private List<ContainerElement> containerField;

        private List<DynamicElement> dynamicField;

		private string keyField;

		[System.Xml.Serialization.XmlElementAttribute("register", Order = 0)]
		public List<RegisterElement> register
		{
			get
			{
				return this.registerField;
			}
			set
			{
				this.registerField = value;
			}
		}

		[System.Xml.Serialization.XmlElementAttribute("dynamic", Order = 2)]
		public List<DynamicElement> dynamic
		{
			get
			{
				return this.dynamicField;
			}
			set
			{
				this.dynamicField = value;
			}
		}

		[System.Xml.Serialization.XmlElementAttribute("container", Order = 1)]
		public List<ContainerElement> container
		{
			get
			{
				return this.containerField;
			}
			set
			{
				this.containerField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string key
		{
			get
			{
				return this.keyField;
			}
			set
			{
				this.keyField = value;
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schema.powerumc.kr/umc/core/ioc")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schema.powerumc.kr/umc/core/ioc", IsNullable = true)]
	public partial class DynamicElement
	{
		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public string type { get; set; }

		[System.Xml.Serialization.XmlElementAttribute(Order = 1)]
		public LifetimeFlagType lifetime { get; set; }
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schema.powerumc.kr/umc/core/ioc")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schema.powerumc.kr/umc/core/ioc", IsNullable = true)]
	public partial class RegisterElement
	{

		private LifetimeElement lifetimeField;

		private List<InterceptorElement> interceptorField;

		private List<ParamElement> constructorField;

		private List<PropertyElement> propertyField;

		private List<MethodElement> methodField;

		private string contractField;

		private string dependencyToField;

		private string keyField;

		[System.Xml.Serialization.XmlElementAttribute(Order = 0)]
		public LifetimeElement lifetime
		{
			get
			{
				return this.lifetimeField;
			}
			set
			{
				this.lifetimeField = value;
			}
		}

		[System.Xml.Serialization.XmlElementAttribute("interceptor", Order = 1)]
		public List<InterceptorElement> interceptor
		{
			get
			{
				return this.interceptorField;
			}
			set
			{
				this.interceptorField = value;
			}
		}

		[System.Xml.Serialization.XmlArrayAttribute(Order = 2)]
		[System.Xml.Serialization.XmlArrayItemAttribute("param", IsNullable = false)]
		public List<ParamElement> constructor
		{
			get
			{
				return this.constructorField;
			}
			set
			{
				this.constructorField = value;
			}
		}

		[System.Xml.Serialization.XmlElementAttribute("property", Order = 3)]
		public List<PropertyElement> property
		{
			get
			{
				return this.propertyField;
			}
			set
			{
				this.propertyField = value;
			}
		}

		[System.Xml.Serialization.XmlElementAttribute("method", Order = 4)]
		public List<MethodElement> method
		{
			get
			{
				return this.methodField;
			}
			set
			{
				this.methodField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string contract
		{
			get
			{
				return this.contractField;
			}
			set
			{
				this.contractField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string dependencyTo
		{
			get
			{
				return this.dependencyToField;
			}
			set
			{
				this.dependencyToField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string key
		{
			get
			{
				return this.keyField;
			}
			set
			{
				this.keyField = value;
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schema.powerumc.kr/umc/core/ioc")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schema.powerumc.kr/umc/core/ioc", IsNullable = true)]
	public partial class LifetimeElement
	{

		private LifetimeFlagType typeField;

		public LifetimeElement()
		{
			this.typeField = LifetimeFlagType.Default;
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		[System.ComponentModel.DefaultValueAttribute(LifetimeFlagType.Default)]
		public LifetimeFlagType type
		{
			get
			{
				return this.typeField;
			}
			set
			{
				this.typeField = value;
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schema.powerumc.kr/umc/core/ioc")]
	public enum LifetimeFlagType
	{

		/// <remarks/>
		Default,

		/// <remarks/>
		PerCall,

		/// <remarks/>
		PerThread,

		/// <remarks/>
		Singleton,

		/// <remarks/>
		External,

		/// <remarks/>
		Hierarchy,

		/// <remarks/>
		Custom,
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schema.powerumc.kr/umc/core/ioc")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schema.powerumc.kr/umc/core/ioc", IsNullable = true)]
	public partial class MethodElement
	{

		private List<ParamElement> paramField;

		private string nameField;

		[System.Xml.Serialization.XmlElementAttribute("param", Order = 0)]
		public List<ParamElement> param
		{
			get
			{
				return this.paramField;
			}
			set
			{
				this.paramField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string name
		{
			get
			{
				return this.nameField;
			}
			set
			{
				this.nameField = value;
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schema.powerumc.kr/umc/core/ioc")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schema.powerumc.kr/umc/core/ioc", IsNullable = true)]
	public partial class ParamElement
	{

		private object itemField;

		private string nameField;

		private string valueField;

		private string typeField;

		[System.Xml.Serialization.XmlElementAttribute("dependency", typeof(DependencyElement), Order = 0)]
		[System.Xml.Serialization.XmlElementAttribute("value", typeof(ValueElement), Order = 0)]
		public object Item
		{
			get
			{
				return this.itemField;
			}
			set
			{
				this.itemField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string name
		{
			get
			{
				return this.nameField;
			}
			set
			{
				this.nameField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string type
		{
			get
			{
				return this.typeField;
			}
			set
			{
				this.typeField = value;
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schema.powerumc.kr/umc/core/ioc")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schema.powerumc.kr/umc/core/ioc", IsNullable = true)]
	public partial class DependencyElement
	{

		private string typeOfContractField;

		private string keyField;

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string typeOfContract
		{
			get
			{
				return this.typeOfContractField;
			}
			set
			{
				this.typeOfContractField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string key
		{
			get
			{
				return this.keyField;
			}
			set
			{
				this.keyField = value;
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schema.powerumc.kr/umc/core/ioc")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schema.powerumc.kr/umc/core/ioc", IsNullable = true)]
	public partial class ValueElement
	{

		private string valueField;

		private string typeField;

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string value
		{
			get
			{
				return this.valueField;
			}
			set
			{
				this.valueField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string type
		{
			get
			{
				return this.typeField;
			}
			set
			{
				this.typeField = value;
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schema.powerumc.kr/umc/core/ioc")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schema.powerumc.kr/umc/core/ioc", IsNullable = true)]
	public partial class PropertyElement
	{

		private object itemField;

		private string nameField;

		[System.Xml.Serialization.XmlElementAttribute("dependency", typeof(DependencyElement), Order = 0)]
		[System.Xml.Serialization.XmlElementAttribute("value", typeof(ValueElement), Order = 0)]
		public object Item
		{
			get
			{
				return this.itemField;
			}
			set
			{
				this.itemField = value;
			}
		}

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string name
		{
			get
			{
				return this.nameField;
			}
			set
			{
				this.nameField = value;
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schema.powerumc.kr/umc/core/ioc")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schema.powerumc.kr/umc/core/ioc", IsNullable = true)]
	public partial class InterceptorElement
	{

		private string typeField;

		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string type
		{
			get
			{
				return this.typeField;
			}
			set
			{
				this.typeField = value;
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schema.powerumc.kr/umc/core/ioc")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schema.powerumc.kr/umc/core/ioc", IsNullable = true)]
	public partial class ContainersElement
	{

		private List<ContainerElement> containerField;

		[System.Xml.Serialization.XmlElementAttribute("container", Order = 0)]
		public List<ContainerElement> container
		{
			get
			{
				return this.containerField;
			}
			set
			{
				this.containerField = value;
			}
		}
	}

	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schema.powerumc.kr/umc/core/ioc")]
	[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schema.powerumc.kr/umc/core/ioc", IsNullable = true)]
	public partial class ConstructorElement
	{

		private List<ParamElement> paramField;

		[System.Xml.Serialization.XmlElementAttribute("param", Order = 0)]
		public List<ParamElement> param
		{
			get
			{
				return this.paramField;
			}
			set
			{
				this.paramField = value;
			}
		}
	}
}
